### ISSUE TITLE
Multiple knives on some aim/awp maps

### ISSUE THREAD

**Issue by Wyll3R** [kgns/weapons#150]
![123](https://user-images.githubusercontent.com/58313115/69833890-5ebe7080-123f-11ea-992d-258358e2fbc4.png)

I know that mp_equipment_reset_rounds 1 can fix that, but it also gives another problem that you cant save any weapon for the next round.

It appears every round, if you survive. On maps, where guns drop every round. (awp_lego_2, Aim_ak47_lego, Aim_Redline)

**Comment by BlackYuzia** [comment]
I have the same.

**Comment by Wyll3R** [comment]
It appears on maps, where is used "game_player_equip", I suppose.

**Comment by kgns** [comment]
try using https://forums.alliedmods.net/showthread.php?t=279263 and see if it makes any difference

**Comment by Wyll3R** [comment]
acts the same as mp_equipment_reset_rounds 1, can not save any weapon, because every round i am getting a new one.

**Comment by kgns** [comment]
when you "save" weapons from previous round on these maps, do you still receive new weapons on round start (and do they fell on the ground because you already have the same type of weapon)?

**Comment by BlackYuzia** [comment]
> when you "save" weapons from previous round on these maps, do you still receive new weapons on round start (and do they fell on the ground because you already have the same type of weapon)?

Yep, in some maps (for example, awp_lego_2) weapons will drop to floor. (like a knife)

**Comment by kgns** [comment]
so you want the new knives to get dropped on the ground instead of having multiple knives equipped, is that correct?

**Comment by Wyll3R** [comment]
Yeah, it would be better than multiple knives equipped.

**Comment by crashzk** [comment]
My question would be, because it only happens on servers in casual modes, currently I have a competitive server, I use the weapons plugin and I don't have this error / bug.

However on my casual servers, such as AWP, JAILBREAK and SURF this BUG happens. As CVAR said `mp_equipment_reset_rounds "1"`, solves the problem, but always resets the player in the new round if he is alive, so he loses all his weapons in the new round.

**Comment by xSL0W** [comment]
same problem here, on an AWP only server. I think it matters what plugins do you use to give players weapons / remove them.

**Comment by crashzk** [comment]
> same problem here, on an AWP only server. I think it matters what plugins do you use to give players weapons / remove them.

I believe it is not linked to other plugins but to the map itself, mainly Surf & AWP maps.

I created an AWP server, even plugins, all the same, except the maps, I left the standard CSGO maps; No BUGS of duplicating knives on the server.

**Comment by turkcodec** [comment]
Are there any solution for that?

**Comment by kgns** [comment]
the problem here is with maps that use game_player_equip to give players weapons on round start/player spawn. by default csgo will give every player a knife, so maps should not be trying to give players knives on spawn. you can remove the entity that gives players knives from the map and recompile it and use it
